
#my:
#  datasource:
#    a:
#      url: jdbc:mysql://rm-2ze1j52h9scfdy357wo.mysql.rds.aliyuncs.com:3306/gtstest1
#      username: gtstest1
#      password: gtstest1!
#    b:
#      url: jdbc:mysql://rm-2ze1j52h9scfdy357wo.mysql.rds.aliyuncs.com:3306/gtstest2
#      username: gtstest2
#      password: gtstest2!

my:
  datasource:
    a:
      url: jdbc:mysql://119.3.123.94:3306/test_a
      username: root
      password: Abc258258!@#
      driverClassName: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 300
      initialSize: 10
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 0
    b:
      url: jdbc:mysql://119.3.123.94:3306/test_b
      username: root
      password: Abc258258!@#
      driverClassName: com.mysql.cj.jdbc.Driver
      filters: stat
      maxActive: 300
      initialSize: 10
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 0
spring:
  application:
    name: seata-demo
  cloud:
    txc:
      txcAppName: seata-demo
      txcServerGroup: txc_test_public.1129361738553704.QD
      url: https://test-cs-gts.aliyuncs.com
server:
  port: 8081
logging:
  level:
    root: DEBUG
    com:
      taobao:
        spas: DEBUG
