---
spring:
  profiles: peer1
  application:
    name: peer
server:
  port: 9999
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka/,http://localhost:9997/eureka/





---
spring:
  profiles: peer2
  application:
    name: peer
server:
  port: 9998
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka/,http://localhost:9997/eureka/


---
spring:
  profiles: peer3
  application:
    name: peer
server:
  port: 9997
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/,http://localhost:9998/eureka/,http://localhost:9997/eureka/






